spring:
  application:
   name: CONFIG-DEV


eureka:
  instance:
    prefer-ip-address: true
  client:
   register-with-eureka: true
   fetch-registery: true
   service-url:
     defaultZone: http://localhost:8085/eureka
